version: '3.8'

services:
  web:
    build: .
    container_name: "rest-api"
    env_file:
      - app.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fullstack

  db:
    image: postgres:13
    container_name: "database"
    env_file:
      - app.env
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack :
    driver: bridge
